export const CREAR_PACIENTE = 'CREAR_PACIENTE';
export const EDITAR_PACINETE = 'EDITAR_PACIENTE';
export const ELIMINAR_PACIENTE = 'ELIMINAR_PACIENTE';
export const PACIENTE_ACTIVO = 'PACIENTE_ACTIVO';
export const QUITAR_PACIENTE = 'QUITAR_PACIENTE';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';